apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: wordpress
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://bitnami-labs.github.io/wordpress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  chart:
    spec:
      chart: wordpress
      version: "6.2.2"
      sourceRef:
        kind: HelmRepository
        name: wordpress
  interval: 1m0s
  values:
    existingSecret: wordpress
    ingress:
      enabled: true
      hostname: wp.rbl.wtf
