apiVersion: v1
kind: Namespace
metadata:
  name: wordpress

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 1m0s
  url: oci://registry-1.docker.io/bitnamicharts/wordpress
  ref:
    tag: latest
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  chart:
    spec:
      chart: wordpress
      version: "6.2.2"
      sourceRef:
        kind: HelmRepository
        name: wordpress
  interval: 1m0s
  values:
    existingSecret: wordpress
    ingress:
      enabled: true
      hostname: wp.rbl.wtf
