apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wordpress
  namespace: wordpress
spec:
  encryptedData:
    wordpressPassword: AgBx63EkNe/YhySYNsfDNf5DubeIUPSWHodZe2+cdWe19LrlB9jWlFBv7bsP879gQRmZqwH0v578vr7c9pQ0Il4u/uf+bjAz1k27LjDn3K/rXurYYrrPLEzQFvvKpQ84RwifsbJIIy6L6Ied/q4+Pg7dOUO9KLoz34C34nt/DXYF3YF7JBzvArs0Pnxo1tKu3wKHsChSNHh0WriEHfG/EuRsEhTN96MnjMOr4YGnKv37J7m8PPt63VCQzI65AY4YVPSkvJ1RVr2JNPhCP6UAutj74qI3c8W8REhKFpLlJMB+oAaqhwxAxuilYJNWe+m6JuPiyiwus+A8tFSmKOnqRTLN/+HogEyMru72SSQcs0EJSlwRMGPuiv7zXy1Wwr3k7dqiKDrbrBRGmay6wBbpViQlCksyXcadekksA23apN+prB2sK+e1noB+4tFNgoFOSK/LdlUGHe68JvYWhNQsL98dJg5w/IYQz6DLT3HNi7Z8PnRKSespT/t41alv7vr1boRZsmeQhb/3ZwKUNcqqAvjv7Fu5L8GllNjQ6UL4A0JnZwismhKjMrl81xfnwwri0B4QQp5wsZXUd1scsZprWMBzpDceg8h7T7Kt0iJ1hG8JA6z9kQKLU01lfKna2IuN1k4w2XGJkm+mdGygdmqxMHNlC8wF3FRCqtNC/f3VRm+BkHi45cZy+QPhC26ddoEI64pySLBUl9P4777dy6Tdin//KRx2E/8=
    wordpressUsername: AgCFPJiYG/wuTKkTou7IIYlDF0v1myLapL0hsCyRaxlI1CT6q4ilWKhAXZiC8cyDhsNGK4rBubOKy8xMW5TMNQuYXewElZJ2LI0qpS939rBQ/KW2CKqNvNdPnIMGAtilr8TIhD86UZOQUp+Sg6Nfx65frPniFDyxgGuhkyahyXKXw7Yi13AaN/Y3DEPIZvND2hOrcO/ObggUsx/6mLArda+aJclroi5IKCUhd+9WulbR7coga6F5SmH2mouASiWd8Y7iVskYQvanTFnGcnbO8Fb0emitCOhbWJJuzyb8x6YYKK53AMXQLQijSPrH1shZhaUtirChGGAG4IdrSoQlb8zGXevptvf9NkBXviODdOd1T6Hlk4plNl4uuhG1UMq9If6LAk4xPKblLrU0p2uDcpTHc011MB1OaIm5HSQUvZRMFM8rU8LqCMlbEQLOVXI5XlIV4nRhCHtWFCFadZLDBT4CnexPYDib9VH9zeklViZlQ/zQjfhpG1E5IjiZ3WJKv7D+PyQsjKIaVmPyOp4QinpOR2f3yDlGfqL4Py9wl3z5qDsasBqcfpoFuEhTZeZVwh7brnvXxgqzGAelahIUnLhnVHSbeeFiATkViM/fhk5a39RfatEjKU4pylQLGK8YEBlisDkWKHU5n2VwOBduLkC2yT6XJNVOupHkZekjds4L2ORIrL1gWEAb+y7SBS819VXsuLa0
  template:
    metadata:
      creationTimestamp: null
      name: wordpress
      namespace: wordpress

