---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: ">5.0.0"
  interval: 1m0s
  releaseName: podinfo
  values:
    replicaCount: 2
    resources:
      annotations:
        cert-manager.io/issuer: "letsencrypt-prod"
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
    hosts:
      - host: test.rbl.wtf
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: letsencrypt-podinfo-test
        hosts:
          - test.rbl.wtf
