---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  chart:
    spec:
      chart: external-dns
      # version: "2.1.8"
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
  interval: 1m0s
  targetNamespace: kube-system
  # values:
