apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner
  namespace: kube-system
spec:
  encryptedData:
    hetzner_token: AgB7kuliiKWCLwHGEQHMxdkDnSV+uu5xol71/doW/rHAE1jdPRCasJTRc4AUj6GdzHwZhysShMn7Ifv31uAIhWio32K/wLFv/cg7LCOQlkHa6a7V/gDl/uuabi2ENxIl5Km2VYdJB/C7h5lcILwYmkKkXrujgfSwZrOtf8me70zK5IscaYYr4jPqtsWxKpYTAHE5wofxZYrfM+6NzMbjI/knP+vKOfeY6k0O0IobqnNUitK0tcRKfk/sbPtIAuqVNi0GEnS9N/sFE44mI80lBxiE9oFi7fsJA1+nE6W5RH2i0YZN95gqqBlwdSsshDOdz+iKcgt7wS/F89R0YVabSfYX3vw/Lz68PLjmZf0eUC+PJXzC6a8+lGbCi77eajwV1+EEfzDxxlfPbw2x75YNlOwuMvAR5a6D6qZyMEWY4LwjH9COTV/z2jtkAIk1+GWf6HH5ddh+YxrI1h2yMfhzjrjUVJxrGeERS5csvEyH8f8afDP6j7c7V/RGXU1kTOaxouS/Y/Mc0ZBxZ/hDfcWMXmhLqw13TBX27gaJp4FYO2mFUi6tVM8DXW9x197i3fhFNOtBj4wnnY0xk3Iqt02q/q8acbSe9IYw5AtiWJ2JiXXemCUUsolFe0WGtoOzipfUHzJcawS14Dkv/AbixHO3vlLdnXFtj6oVQMqHvUCi8Pa6UrMUF0H4URh3dJZSDhh5nry7rOZLjTeS8dvFcftKXPnul4bA4amB6WvRVPV8WQKN0/DIHSsKa/AoQZ+CCWfqActMmoYpdOFTDcbyFOlun+H5
  template:
    metadata:
      creationTimestamp: null
      name: hetzner
      namespace: kube-system

